FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY Apps/MobileApp/MobileApp.csproj Apps/MobileApp/
RUN dotnet restore "Apps/MobileApp/MobileApp.csproj"
COPY . .
WORKDIR "/src/Apps/MobileApp"
RUN dotnet build "MobileApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MobileApp.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MobileApp.dll"]
